"""initial tables

Revision ID: 21260cc607ff
Revises: 
Create Date: 2026-04-12 18:50:45.847577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21260cc607ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_semana',
    sa.Column('id_dia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_dia'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('especialidad',
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidad'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidad_id_especialidad'), 'especialidad', ['id_especialidad'], unique=False)
    op.create_table('hospital',
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_hospital')
    )
    op.create_index(op.f('ix_hospital_id_hospital'), 'hospital', ['id_hospital'], unique=False)
    op.create_table('obra_social',
    sa.Column('id_obra_social', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_obra_social'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_obra_social_id_obra_social'), 'obra_social', ['id_obra_social'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_obra_social', sa.Integer(), nullable=True),
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id_hospital'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_obra_social'], ['obra_social.id_obra_social'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_index(op.f('ix_paciente_dni'), 'paciente', ['dni'], unique=False)
    op.create_index(op.f('ix_paciente_id_paciente'), 'paciente', ['id_paciente'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id_hospital'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('medico',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id_hospital'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_medico'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_medico_id_medico'), 'medico', ['id_medico'], unique=False)
    op.create_table('disponibilidad_medico',
    sa.Column('id_disponibilidad', sa.Integer(), nullable=False),
    sa.Column('turno_manana', sa.Boolean(), nullable=False),
    sa.Column('hora_inicio_manana', sa.Time(), nullable=True),
    sa.Column('hora_fin_manana', sa.Time(), nullable=True),
    sa.Column('turno_tarde', sa.Boolean(), nullable=False),
    sa.Column('hora_inicio_tarde', sa.Time(), nullable=True),
    sa.Column('hora_fin_tarde', sa.Time(), nullable=True),
    sa.Column('duracion_turno_minutos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_dia', sa.Integer(), nullable=False),
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dia'], ['dia_semana.id_dia'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id_hospital'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id_medico'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_disponibilidad'),
    sa.UniqueConstraint('id_medico', 'id_dia', 'id_hospital', name='uq_disponibilidad_medico_dia_hospital')
    )
    op.create_index(op.f('ix_disponibilidad_medico_id_disponibilidad'), 'disponibilidad_medico', ['id_disponibilidad'], unique=False)
    op.create_table('turno',
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('motivo_consulta', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id_hospital'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id_medico'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_turno')
    )
    op.create_index(op.f('ix_turno_fecha'), 'turno', ['fecha'], unique=False)
    op.create_index(op.f('ix_turno_id_medico'), 'turno', ['id_medico'], unique=False)
    op.create_index(op.f('ix_turno_id_paciente'), 'turno', ['id_paciente'], unique=False)
    op.create_index(op.f('ix_turno_id_turno'), 'turno', ['id_turno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turno_id_turno'), table_name='turno')
    op.drop_index(op.f('ix_turno_id_paciente'), table_name='turno')
    op.drop_index(op.f('ix_turno_id_medico'), table_name='turno')
    op.drop_index(op.f('ix_turno_fecha'), table_name='turno')
    op.drop_table('turno')
    op.drop_index(op.f('ix_disponibilidad_medico_id_disponibilidad'), table_name='disponibilidad_medico')
    op.drop_table('disponibilidad_medico')
    op.drop_index(op.f('ix_medico_id_medico'), table_name='medico')
    op.drop_table('medico')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_paciente_id_paciente'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_dni'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_obra_social_id_obra_social'), table_name='obra_social')
    op.drop_table('obra_social')
    op.drop_index(op.f('ix_hospital_id_hospital'), table_name='hospital')
    op.drop_table('hospital')
    op.drop_index(op.f('ix_especialidad_id_especialidad'), table_name='especialidad')
    op.drop_table('especialidad')
    op.drop_table('dia_semana')
    # ### end Alembic commands ###
